export default {
    SCRIPT: 0,
    PHYSICS: 1,
    DIRECTIONAL_SHADOWS: 2,
    OMNIDIRECTIONAL_SHADOWS: 3,
    AMBIENT_OCCLUSION: 4,
    OPAQUE: 5,
    TRANSPARENCY: 6,
    SPRITE: 7,
    DECAL: 8,
    SSGI: 9,
    LENS: 10,
    MOTION_BLUR: 11,
    FRAME_COMPOSITION: 12,
    VISIBILITY: 13,
    SSAO: 14,
    BLOOM: 15,
    BOKEH: 16,
    ATMOSPHERE: 17
}

export const REVERSED_METRICS_FLAGS = {
    "0": "SCRIPT",
    "1": "PHYSICS",
    "2": "DIRECTIONAL_SHADOWS",
    "3": "OMNIDIRECTIONAL_SHADOWS",
    "4": "AMBIENT_OCCLUSION",
    "5": "OPAQUE",
    "6": "TRANSPARENCY",
    "7": "SPRITE",
    "8": "DECAL",
    "9": "SSGI",
    "10": "LENS",
    "11": "MOTION_BLUR",
    "12": "FRAME_COMPOSITION",
    "13": "VISIBILITY",
    "14": "SSAO",
    "15": "BLOOM",
    "16": "BOKEH",
    "17": "ATMOSPHERE"
}
