export default {
    TRANSFORM: 'TransformComponent',
    CUBE_MAP: 'CubeMapComponent',
    COLLIDER: 'ColliderComponent',
    DIRECTIONAL_LIGHT:'DirectionalLightComponent',
    POINT_LIGHT: 'PointLightComponent',
    PICK: 'PickComponent',
    SPOT_LIGHT: 'SpotLightComponent',
    FOLDER: 'FolderComponent',
    MATERIAL: 'MaterialComponent',
    MESH: 'MeshComponent',
    PHYSICS: 'PhysicsBodyComponent',
    SKYBOX: 'SkyboxComponent',
    TERRAIN: 'TerrainComponent',
    SKYLIGHT: 'SkylightComponent',
    SCRIPT: 'ScriptComponent',
    CAMERA: 'CameraComponent',
    LINE: 'LineComponent',
    PROBE: 'ProbeComponent'
}