export default {
    CULLING: "0",
    SCRIPT: "1",
    TRANSFORMATION: "2",
    DEPTH_PRE_PASS: "3",
    AO: "4",
    CUBE_MAP: "5",
    SHADOWS: "6",
    PERF: "7",
    PHYSICS: "8",
    MESH: "9",
    FORWARD: "10",
    LINE: "11",
    SSGI: "12",
    PICK: "14",
    PROBE: "15",
}